source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "bootsnap", require: false
gem "rails", "~>7.1.0"
gem "sprockets-rails"
gem "sqlite3", "~> 1.4"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "bard-file_field", path: ".."

group :development do
  gem "web-console"
end

group :test do
  gem "simplecov"
  gem "cucumber-rails", require: false
  gem "cucumber", require: false, github: "botandrose/cucumber", branch: "restore_looser_line_numbers"
  gem "cuprite-downloads"
  gem "puma"
  gem "capybara-screenshot"
  gem "capybara-shadowdom"
  gem "database_cleaner"
  gem "rspec-rails"
  gem "byebug"
end

