# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative "config/application"

Rails.application.load_tasks

require 'cucumber/rake/task'

Cucumber::Rake::Task.new({:default => 'test:prepare'}, 'Run features that should pass') do |t|
  t.fork = true # You may get faster startup if you set this to false
  t.profile = 'default'
end
